### ISSUE TITLE
US 01.05.01 E - WL - Second Chance to be Chosen

### ISSUE THREAD

**Issue by ruchali1** [CMPUT301F24nachos/nachos-business#10]
Lottery entrants, should be give a second opportunity to be selected for the event if a chosen participant opts-out, i.e. should do another pull from the waiting list with remaining entrants. 

_Assumption_: the entrant does not need to specify to be given a second chance, but will be automatically given one in the case where a spot remains open. #27 

Associated Features 

- [x] #77

Associated User Stories

- [ ]  #27

**Comment by ErenPaper** [comment]
#77

**Comment by aabrady6** [comment]
Users who are in the waitlist will always be given second chance to be picked. Will implement in #27 the functionality for selecting a new user when a user declines.
