### ISSUE TITLE
Organizer - Generate and edit facility profiles

### ISSUE THREAD

**Issue by Enragedsaladss** [CMPUT301F24nachos/nachos-business#66]
Organizers should be able to create and ~~edit multiple facility profiles~~ edit a single facility profile which can be attached to event detail pages and viewed by entrants. When create an event there should be an option to create a new facility (if one has not been created by the organizer) or choose ~~from one of~~ the organizers existing facilities. Any created facility profile should be saved for the organizer and be edited whenever.

Associated User Stories 

- [x] #117

**Comment by aabrady6** [comment]
complete
