### ISSUE TITLE
Entrant - Implement Opt-Out Notification Functionality

### ISSUE THREAD

**Issue by ErenPaper** [CMPUT301F24nachos/nachos-business#75]
The ability to opt out of receiving notifications sent by the admin and event organizers. Users can select an option to disable notifications through a button, and the system will ensure that no further alerts are sent to those who have chosen to opt out. The backend will handle these preferences and adjust the notification logic accordingly. 

Users can receive confirmation that they have successfully opted out, and this preference should be easily reversible.

Associated User  Stories

- [ ]  #9

**Comment by nopunindented** [comment]
- Former halfway point
