### ISSUE TITLE
Entrants - Implement Second Chance Selection Functionality

### ISSUE THREAD

**Issue by ErenPaper** [CMPUT301F24nachos/nachos-business#77]
Automatically be given a second opportunity to be selected for an event if a previously chosen participant opts out. This feature will need to implement logic to check for available spots whenever an entrant opts out and subsequently perform another search in the waiting list. The system should manage the waiting list dynamically, ensuring that remaining entrants are considered for selection without requiring them to take any action. 

Associated User  Stories

- [ ]  #10

**Comment by aabrady6** [comment]
Users who are in the waitlist will always be given second chance to be picked. Will implement in #10 the functionality for selecting a new user when a user declines.
