### ISSUE TITLE
Entrants - Implement Accept Invitation/Sign Up Functionality

### ISSUE THREAD

**Issue by ErenPaper** [CMPUT301F24nachos/nachos-business#78]
Entrants chosen for an event can accept their invitation and officially sign up for the event. This feature will be integrated into the notification system, where users receive an alert when selected. The system will provide a clear "Accept" button that entrants can click to confirm their participation within the notification. When accepted, the backend will update the user's status in the database to reflect their registration for the event. 

Users may also be prompted with additional event details after.

Associated User  Stories

- [ ]  #11

**Comment by nopunindented** [comment]
- Former halfway point
